export const contacts = [
  {name: 'Godwin', phone: '', email: '', address:'Carosammy - Makurdi'},
  {name: 'Chimezie', phone: '', email: '', address:'Ziknic - Suleja'},
  {name: 'Jude', phone: '', email: '', address: 'PulseConnect - Keffi'},
  {name: 'Phillip', phone: '', email: '', address: 'Yisab - Lokoja'},
  {name: 'Gabriel', phone: '', email: '', address: 'Ziknik - Minna'},
  {name: 'Stephen', phone: '', email: '', address: 'Ziknik - Minna'},
  {name: 'Victor', phone: '', email: '', address: 'Touch - Kaduna'},
  {name: 'Blessing', phone: '', email: '', address: 'Midas Touch - Kaduna'},
  {name: 'Ezeh Ndidi', phone: '', email: '', address: 'Mecca Media - Abuja'},
  {name: 'Muritala', phone: '', email: '', address: 'Magic Brother - Abuja'},
  {name: 'Deborah', phone: '', email: '', address: 'Magic Brother - Abuja'},
  {name: 'Rhoda', phone: '', email: '', address: 'Elohim Gadgets - Abuja'},
  {name: 'Onyedikachi', phone: '', email: '', address: 'Ndubest - Gboko'},
  {name: 'John Abutu', phone: '', email: '', address: 'May Royal - Otukpo'},
  {name: 'Samson', phone: '', email: '', address: 'Mosie Solid Hub - Kuje'},
  {name: 'Esther', phone: '', email: '', address: 'Dynasteia - Gwagwalada'},
  {name: 'Matthew', phone: '', email: '', address: 'Darigo Comm - Lafia'},
  {name: 'Noah', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Esther', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Evelyn', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Michael', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Grace', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Aliyu', phone: '', email: '', address: 'OSC Abuja'},
  {name: 'Khalifa', phone: '', email: '', address: 'Smartphone Global Service - Jigawa'},
  {name: 'Joseph', phone: '', email: '', address: 'Smartphone Global Service - Katsina'},
  {name: 'Emmanuella', phone: '', email: '', address: 'Smartphone Global Service - Funtua'},
  {name: 'Hmad', phone: '', email: '', address: 'Reedlim Global Enterprise - Bauchi'},
  {name: 'Abdulmalik', phone: '', email: '', address: 'Reedlim Global Enterprise - Gombe'},
  {name: 'Nkiru', phone: '', email: '', address: 'Midas Touch - Jos'},
  {name: 'Yusuf', phone: '', email: '', address: 'Midas Touch - Sokoto'},
  {name: 'Bana', phone: '', email: '', address: 'ASC-M - Zikniks - Maiduguri'},
  {name: 'Bana', phone: '', email: '', address: 'ASC-M - Don Yellow'},
  {name: 'Andrew', phone: '', email: '', address: 'Ustaz Exclusive Store - Jalingo'},
  {name: 'Haruna', phone: '', email: '', address: 'Nakia Communications Hadeja - Dutse'},
  {name: 'Suleiman', phone: '', email: '', address: 'CP Smartphone Global Service - Damaturu'},
  {name: 'Shadrack', phone: '', email: '', address: 'Switrat Limited - Mubbi'},
  {name: 'Jibrin', phone: '', email: '', address: 'CP Jibo Venture - Zamfara'},
  {name: 'Rejoice', phone: '', email: '', address: 'ASC-M-Crescita Global Resources Ltd - Adamawa'},
];